---
- name: Windows post provisioning  
  hosts: "{{ VMware_VM_IP_address }}"
  gather_facts: no
  collections:
    - ansible.windows
    - community.vmware
    - community.windows
  tasks:
    - block:
        - name: Validate and set the system timezone
          import_role:
            name: timezone

        - name: KMS OS registration
          import_role:
            name: kms_registration

        - name: Enable the RDP
          import_role:
            name: enable_rdp
        
        - name: Disable the firewall rules
          import_role:
            name: disable_firewall

        - name: Disk Management
          import_role:
            name: disk_management

        - name: FlexNet Installation
          import_role:
            name: flexnet_installation   

        - name: Onboarding the Defender
          import_role:
            name: defender_onboarding

        # - name: Adding the DNS Suffix
        #   import_role:
        #     name: dns_suffix_add

        - name: Qualys Installation
          import_role:
            name: qualys_installation

        # - name: Splunk Installation
        #   import_role:
        #     name: splunk_agent
        # - name: Validate and set the system timezone
        #   import_role:
        #     name: test


      rescue:
        - name: Set failure message to be used in the next workflow
          ansible.builtin.set_fact:
            error_message: "1. Infoblox alloted the IP {{ VMware_VM_IP_address }} for {{ VMware_VM_name }}.\n2. Server {{ VMware_VM_name }} built successfully.\n3. Server added into ansible inventory.\n4. Server {{ VMware_VM_name }} joined the domain.\nBut failure happend during post-provisioning tasks.\nError detail: {{ ansible_failed_result.msg }}"
          when: ansible_failed_result is defined

        - name: Forward failure message
          ansible.builtin.set_stats:
            data:
              error_message: "{{ error_message }}"
          when: ansible_failed_result is defined

        - name: Fail the playbook if there is an error
          ansible.builtin.fail:
            msg: "Playbook failed during execution. Error message: {{ error_message }}"
          when: ansible_failed_result is defined
